
// This file was generated by executing this statement: wav2c 56489__moonscythe__laser.wav
extern uint16_t laserwav[];
#define LASER1_WAV_SAMPLE_RATE 441000
#define LASER1_WAV_BITS_PER_SAMPLE 16
#define LASER1_WAV_NUMBER_OF_SAMPLES 38912